services:
  app:
    build:
      context: ./app
      args:
        - APP_PORT=${APP_PORT}
        - APP_HOST=${APP_HOST}
        - API_PORT=${API_PORT}
        - API_HOST=${API_HOST}
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - ./app:/app
      - /app/node_modules
  api:
    build:
      context: ./api
      args:
        - API_PORT=${API_PORT}
    ports:
      - '${API_PORT}:${API_PORT}'
    volumes:
      - ./api:/api
