services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
      args:
        - API_PORT=${API_PORT}
    ports:
      - '${APP_PORT}:3000'
    restart: unless-stopped
  api:
    build:
      context: ./api
    ports:
      - '${API_PORT}:80'
    restart: unless-stopped
